config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  root to: "main#index"

  get "sign-up", to: "registrations#new"
  post "sign-up", to: "registrations#create"
  
  get "sign-in", to: "sessions#new"
  post "sign-in", to: "sessions#create"

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  get "password/reset", to: "passwords_resets#new"
  post "password/reset", to: "passwords_resets#create"
  get "password/reset/edit", to: "passwords_resets#edit"
  patch "password/reset/edit", to: "passwords_resets#update"
  
  delete "logout", to: "sessions#destroy"

  get "auth/twitter/callback", to: "omniauth_callbacks#twitter"

  resources :twitter_accounts
  resources :tweets

  get "about", to: "pages#about"

  require 'sidekiq/web'

  ScheduledTweets::Application.routes.draw do
    mount Sidekiq::Web => "/sidekiq"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :twitter_account

  validates :body, length: { minimum: 1, maximum: 280 }
  validates :published_at, presence: true

  after_initialize do
    self.published_at ||= 1.hour.from_now
  end

  after_save_commit do
    if published_at_previously_changed?
      TweetJob.set(wait_until: published_at).perform_later(self)
    end
  end

  def published?
    tweet_id?
  end

  def publish_to_twitter!
    tweet = twitter_account.client.update(body)
    update(tweet_id: tweet.id)
  end
end

app/models/twitter_account.rb
class TwitterAccount < ApplicationRecord
  belongs_to :user
  has_many :tweets, dependent: :destroy

  validates :username, uniqueness: true

  def client
    Twitter::REST::Client.new do |config|
      config.consumer_key        = Rails.application.credentials.dig(:twitter, :api_key)
      config.consumer_secret     = Rails.application.credentials.dig(:twitter, :api_secret)
      config.access_token        = token
      config.access_token_secret = secret
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :twitter_accounts
  has_many :tweets
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, 
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user
  
  def set_current_user
    if session[:user_id]
      Current.user = User.find_by(id: session[:user_id])
    end
  end

  def require_user_logged_in!
    redirect_to sign_in_path, alert: "You must be logged in" if Current.user.nil?
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController
  def twitter
    twitter_account = Current.user.twitter_accounts.where(username: auth.info.nickname).first_or_initialize
    twitter_account.update(
      name: auth.info.name,
      image: auth.info.image,
      token: auth.credentials.token,
      secret: auth.credentials.secret
    )
    redirect_to twitter_accounts_path, notice: "Successfully connected your Twitter account."
  end

  def auth
    request.env["omniauth.auth"]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :require_user_logged_in!

  def edit
  end

  def update
    if Current.user.update(password_params)
      redirect_to root_path, notice: "Password Updated!"
    else
      render :edit
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/passwords_resets_controller.rb
class PasswordsResetsController < ApplicationController
  def edit
  end

  def create
    @user = User.find_by(email: params[:email])

    if @user.present?
      PasswordMailer.with(user: @user).reset.deliver_now
    end
    
    redirect_to root_path, notice: "If account with that email was found, we have sent an email with password reset link"
  end

  def edit
    @user = User.find_signed(params[:token], purpose: "password_reset")
  rescue ActiveSupport::MessageVerifier::InvalidSignature
    redirect_to sign_in_path, alert: "Your token has expired"  
  end

  def update
    @user = User.find_signed(params[:token], purpose: "password_reset")
    if @user.update(password_params)
      redirect_to sign_in_path, notice: "Your password was reset successfully. Please sign in."
    else
      render :edit
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Successfully Created an Account"
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Successfully Logged In"
    else
      flash[:alert] = "Invalid Credentials"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Successfully Logged Out"
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :require_user_logged_in!
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  
  def index
    @tweets = Current.user.tweets
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Current.user.tweets.create(tweet_params)
    if @tweet.save
      redirect_to tweets_path, notice: "Tweet was scheduled successfully"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @tweet.update(tweet_params)
      redirect_to tweets_path, notice: "Successfully updated tweet."
    else
      render :edit
    end
  end

  def destroy
    @tweet.destroy
    redirect_to tweets_path, notice: "Tweet was unscheduled and deleted."
  end

  private

  def tweet_params
    params.require(:tweet).permit(:twitter_account_id, :body, :published_at)
  end

  def set_tweet
    @tweet = Current.user.tweets.find(params[:id])
  end

end

app/controllers/twitter_accounts_controller.rb
class TwitterAccountsController < ApplicationController
  before_action :require_user_logged_in!
  before_action :set_twitter_account, only: [:destroy]

  def index
    @twitter_accounts = Current.user.twitter_accounts
  end

  def destroy
    @twitter_account.destroy
    redirect_to twitter_accounts_path, notice: "Successfully disconnected the account."
  end

  private

  def set_twitter_account
    @twitter_account = Current.user.twitter_accounts.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduledTweets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <div class="container">
      <%= render partial: "shared/flash_messages" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex justify-content-center align-items-center">
  <h1>Welcome to Scheduled Tweets</h1>
</div>

<% if Current.user %>
  <div class="d-flex justify-content-center align-items-center mt-5">
    <%= button_to "Connect Twitter", "/auth/twitter", class: "btn btn-primary", method: :post %>
  </div>
<% end %>

app/views/pages/about.html.erb
<div class="d-flex justify-content-center align-items-center">
  <h1>About Us</h1>
</div>

app/views/passwords_resets/edit.html.erb
<div class="d-flex justify-content-center align-items-center mt-5">
  <h1>Reset Your Password</h1>
</div>

<div class="form-wrapper shadow">
  <%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |f| %>
    <% if f.object.errors.any? %>
      <div class="alert alert-danger">
        <% f.object.errors.full_messages.each do |message| %>
          <p><%= message %></p>
        <% end %>
      </div>
    <% end %>

    <div class="mb-3">
      <%= f.label :password, class: "form-label" %>
      <%= f.password_field :password, class: "form-control", placeholder: "password" %>
    </div>
    
    <div class="mb-3">
      <%= f.label :password_confirmation, class: "form-label" %>
      <%= f.password_field :password_confirmation, class: "form-control", placeholder: "password" %>
    </div>

    <%= f.submit "Reset Password", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/passwords_resets/new.html.erb
<div class="d-flex justify-content-center align-items-center mt-5">
  <h1>Forgot Your Password?</h1>
</div>

<div class="form-wrapper shadow">
  <%= form_with url: password_reset_path do |f| %>
    <div class="mb-3">
      <%= f.label :email, class: "form-label" %>
      <%= f.email_field :email, class: "form-control", placeholder: "steve@apple.com" %>
    </div>

    <%= f.submit "Reset Password", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/shared/_flash_messages.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info mt-4 alert-dismissible fade show" role="alert">
    <%= flash[:notice] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-danger mt-4 alert-dismissible fade show" role="alert">
    <%= flash[:alert] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_form_errors.html.erb
<% if form.object.errors.any? %>
  <div class="alert alert-danger">
    <% form.object.errors.full_messages.each do |message| %>
      <p><%= message %></p>
    <% end %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Scheduled Tweets", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Tweets", tweets_path, class: "nav-link active", aria: { current: "page" } %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Twitter Accounts", twitter_accounts_path, class: "nav-link" %>
        </li>
      </ul>

      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if Current.user %>
          <li class="nav-item d-flex align-items-center me-3">
            <%= link_to Current.user.email, edit_password_path %>
          </li>
          <li class="nav-item">
            <%= button_to "Log Out", logout_path, class: "btn btn-outline-primary", method: :delete %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", sign_in_path, class: "btn btn-outline-primary me-3" %> 
          </li> 
          <li class="nav-item">
            <%= link_to "Create Account", sign_up_path, class: "btn btn-primary" %>
          </li>  
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/tweets/_form.html.erb
<%= form_with model: tweet do |form| %>
  <%= render "shared/form_errors", form: form %>
  <div class="mb-3">
    <%= form.label :twitter_account_id %>
    <%= form.collection_select :twitter_account_id, Current.user.twitter_accounts, :id, :username, {}, { class: "form-select" } %>
  </div>

  <div class="mb-3">
    <%= form.label :body %>
    <%= form.text_area :body, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :published_at %>
    <div class="form-control">
      <%= form.datetime_select :published_at %>
    </div>
  </div>

  <%= form.button "Schedule a Tweet", class: "btn btn-primary" %>
  <% if form.object.persisted? %>
    <%= link_to "Delete", form.object, method: :delete, data: { confirm: "Are You Sure?" }, class: "btn btn-outline-danger" %>
  <% end %>
<% end %>

app/views/tweets/_tweet.html.erb
<div class="tweet mb-3 border border-1 rounded p-3 col-sm-6 ms-auto me-auto">
  <div class="mb-2">
    <%= tweet.body %>
  </div>
  <div class="d-flex align-items-center mb-3">
    <%= image_tag tweet.twitter_account.image, class: "rounded-circle me-3" %>
    <%= link_to "@#{tweet.twitter_account.username}", "https://twitter.com/#{tweet.twitter_account.username}", target: :_blank %>
  </div>

  <% if tweet.published? %>
    <%= link_to "View Tweet", "https://twitter.com/#{tweet.twitter_account.username}/status/#{tweet.tweet_id}" %>
  <% else %>
    <p><strong>Scheduled for:</strong> <%= l tweet.published_at, format: :long %></p>
    <%= link_to "Edit", edit_tweet_path(tweet) %>
  <% end %>
</div>

app/views/tweets/edit.html.erb
<header class="d-flex justify-content-between align-items-center mb-5">
  <h1>Edit Scheduled Tweet</h1>
  <%= link_to "Back to Tweets", tweets_path %>
</header>

<%= render "form", tweet: @tweet %>

app/views/tweets/index.html.erb
<header class="d-flex justify-content-between align-items-center mb-5">
  <h1>Tweets</h1>

  <% if Current.user.twitter_accounts.any? %>
    <%= link_to "Schedule a Tweet", new_tweet_path, class: "btn btn-primary" %>
  <% end %>
</header>

<% if Current.user.twitter_accounts.none? %>
  <%= link_to "Connect Your Twitter Account", "auth/twitter", method: :post, class: "btn btn-primary" %>
<% end %>

<div id="tweets-list">
  <%= render @tweets %>
</div>

app/views/tweets/new.html.erb
<header class="d-flex justify-content-between align-items-center mb-5">
  <h1>Schedule a Tweet</h1>
</header>

<%= render "form", tweet: @tweet %>

app/views/twitter_accounts/index.html.erb
<header class="d-flex justify-content-between align-items-center mb-5 pt-5 pb-5">
  <h1>Twitter Accounts</h1>
  <%= link_to "Connect Twitter Account", "auth/twitter", class: "btn btn-primary", method: :post %>
</header>

<% @twitter_accounts.each do |twitter_account| %>
  <div class="d-flex align-items-center mb-3">
    <%= image_tag twitter_account.image, class: "rounded-circle me-3" %>
    <%= link_to "@#{twitter_account.username}", "https://twitter.com/#{twitter_account.username}", target: :_blank %>
  </div>
  <%= button_to "Disconnect", twitter_account, method: :delete, data: { confirm: "Are You Sure?" }, class: "btn btn-danger" %>
<% end %>